---
- name: Create sources link
  file:
    src: /hostdir/sources
    dest: /srv/www/sources
    state: link

- name: Configure webserver
  include_role:
    name: nginx
    tasks_from: base-site
  vars:
    - site:
        name: sources
        urls:
          - sources.voidlinux.eu
          - sources.voidlinux.org
        root_path: /srv/www/sources
        autoindex: true
        use_ssl: "{{ void_aquire_certs }}"
        ssl_certificate_path: "{{ sources_site_cert_path | default('/dev/null') }}"
        ssl_key_path: "{{ sources_site_key_path | default('/dev/null') }}"
        ssl_stapling: yes
