---
- name: Install Packages
  xbps:
    pkg:
      - nebula
    state: present

- name: Create Configuration Directory
  file:
    path: /etc/nebula
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Install Keys
  copy:
    src: "secret/vpn/{{ item }}"
    dest: "/etc/nebula/{{ item }}"
    owner: root
    group: root
    mode: 0600
  with_items:
    - ca.crt
    - "{{network_hostname + '.crt'}}"
    - "{{network_hostname + '.key'}}"

- name: Install Configuration
  template:
    src: config.yml.j2
    dest: /etc/nebula/config.yml
    owner: root
    group: root
    mode: 0600
  notify:
    - nebula

- name: Install Firewall Rules
  copy:
    src: nebula.rules
    dest: /etc/iptables.d/nebula.rules
    owner: root
    group: root
    mode: 0640
  notify:
    - iptables

- name: Enable Service
  service:
    name: nebula
    state: started
    enabled: true
