---
- name: Create Repo Directory
  file:
    path: /srv/www/void-repo
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create xlocate group
  group:
    name: xlocate
    state: present

- name: Create Static Mirror Directories
  file:
    path: "/srv/www/void-repo/{{ item.name }}"
    state: directory
    owner: "{{ item.owner|default('root') }}"
    group: "{{ item.group|default('root') }}"
    mode: "{{ item.mode|default(0755) }}"
  with_items:
    - name: distfiles
    - name: live
    - name: logos
    - name: static
    - name: current
      owner: void-buildslave
      group: void-repo
      mode: '0775'
    - name: xlocate
      group: xlocate
      mode: '0775'
  loop_control:
    label: "{{ item.name }}"

- name: Mount the package filesystem into the mirror
  mount:
    fstype: none
    src: /hostdir/binpkgs
    path: /srv/www/void-repo/current
    state: mounted
    opts: defaults,bind,ro
