[core]
  home="/var/lib/netauth"
  server="netauth.voidlinux.org"
  port=1729

[server]
  bind=""
  port=1729

[tls]
  key="/var/lib/netauth/keys/tls.key"
  certificate="/var/lib/netauth/keys/tls.pem"

[token]
  backend = "jwt-rsa"
  lifetime = "20m"
  renewals = 0

[db]
  backend = "ProtoDB"

[crypto]
  backend = "bcrypt"

  [crypto.bcrypt]
    cost = 10

[ldap]
  domain = "voidlinux.org"
