---
network_interfaces:
  - name: eno1
    mode: static
    mode6: disabled
    resolvermode: static
    resolvermode6: disabled
    addresses:
      - 199.168.97.186/29
    resolvers:
      - 8.8.8.8
    routers:
      - 199.168.97.185

xbps_repository_address: alpha.de.repo.voidlinux.org
xbps_repository_main: http://{{ xbps_repository_address }}/current/musl
xbps_repository_nonfree: http://{{ xbps_repository_address }}/current/musl/nonfree
xbps_repository_multilib: http://{{ xbps_repository_address }}/current/musl/multilib
xbps_repository_multilib_nonfree: http://{{ xbps_repository_address }}/current/musl/multilib/nonfree

netlogon_use_cache: false

nomad_host_volumes:
  - name: root_mirror
    path: /data/root_mirror
    read_only: false
