---
xbps_repository_main: /mnt/data/pkgs
xbps_repository_nonfree: /mnt/data/pkgs/nonfree
xbps_repository_multilib: /mnt/data/pkgs/multilib
xbps_repository_multilib_nonfree: /mnt/data/pkgs/multilib/nonfree

sshd_AllowGroups:
  - build-ops
  - syncpeers
