---
xbps_repository_main: /mnt/data/pkgs
xbps_repository_nonfree: /mnt/data/pkgs/nonfree
xbps_repository_multilib: /mnt/data/pkgs/multilib
xbps_repository_multilib_nonfree: /mnt/data/pkgs/multilib/nonfree

sshd_AllowGroups:
  - build-ops
  - syncpeers

buildslave_zone: FI-2

nomad_host_volumes:
  - name: void-packages
    path: /mnt/data/void-packages
    read_only: false
  - name: minio-data
    path: /mnt/data/minio
    read_only: false
  - name: root-pkgs
    path: /mnt/data/pkgs
    read_only: false
  - name: glibc_hostdir
    path: /hostdir
    read_only: false
