---
void_aquire_certs: false

buildslave_zone: FI-2
buildslave_isremote: false

nomad_host_volumes:
  - name: void-packages
    path: /mnt/data/void-packages
    read_only: false
  - name: minio-data
    path: /mnt/data/minio
    read_only: false
  - name: root-pkgs
    path: /mnt/data/pkgs
    read_only: false
