---
network_input_policy: DROP
network_output_policy: ACCEPT

network_interfaces:
  - name: eth0
    mode: static
    mode6: static
    resolvermode: static
    resolvermode6: static
    addresses:
      - 172.31.1.100/24
    resolvers:
      - 8.8.8.8
      - 8.8.4.4
    routers:
      - 172.31.1.1
    addresses6:
      - 2a01:4f8:c17:da9::2/64
    resolvers6:
      - 2001:4860:4860::8888
      - 2001:4860:4860::8844

grafana:
  urls:
    - monitor.voidlinux.com
    - monitor.infrastructure.voidlinux.com
    - monitor.voidlinux.org
  ssl_certificate_path: /var/lib/acme/live/monitor.voidlinux.com/fullchain
  ssl_key_path: /var/lib/acme/live/monitor.voidlinux.com/privkey

acmetool:
  sites:
    - site: monitor.voidlinux.com
      names:
        - monitor.voidlinux.com
        - monitor.infrastructure.voidlinux.com
        - monitor.voidlinux.org
  hostmaster_email: postmaster@voidlinux.org
  services:
    - nginx
