---
xbps_repository_address: alpha.de.repo.voidlinux.org
xbps_repository_main: http://{{ xbps_repository_address }}/current
xbps_repository_nonfree: http://{{ xbps_repository_address }}/current/nonfree
xbps_repository_multilib: http://{{ xbps_repository_address }}/current/multilib
xbps_repository_multilib_nonfree: http://{{ xbps_repository_address }}/current/multilib/nonfree
xbps_repository_port: 80


sshd_listen_addresses:
  - 198.204.250.219

sshd_AllowGroups:
  - build-ops
  - syncpeers

live_mirror_bindip: 198.204.250.219

live_mirror_servernames:
  - vm1.a-mci-us.m.voidlinux.org
  - alpha.us.repo.voidlinux.org
  - repo.voidlinux.us
  - repo3.voidlinux.net
  - repo3.voidlinux.com

live_mirror_srvdir: /repo
live_mirror_syncdstdir: /repo
live_mirror_sharename: repo
live_mirror_nodebug: true
live_mirror_use_ssl: true
live_mirror_cert_path: /var/lib/acme/live/vm1.a-mci-us.m.voidlinux.org/fullchain
live_mirror_certkey_path: /var/lib/acme/live/vm1.a-mci-us.m.voidlinux.org/privkey

buildslave_user: buildbot
buildslave_hostdir_owner: buildbot
buildslave_sync_user: xbps-master
buildslave_rootdir: /home/buildbot
buildslave_zone: US-MCI

acmetool:
  sites:
    - site: vm1.a-mci-us.m.voidlinux.org
      names:
        - vm1.a-mci-us.m.voidlinux.org
        - alpha.us.repo.voidlinux.org
  hostmaster_email: postmaster@voidlinux.org
  services:
    - nginx
