---
network_input_policy: DROP
network_output_policy: DROP

network_interfaces:
  - name: eth0
    mode: static
    mode6: disabled
    resolvermode: static
    addresses:
      - 148.251.199.117/32
    resolvers:
      - 213.133.99.99
    routers:
      - 136.243.133.13
  - name: eth1
    mode: disabled
    mode6: static
    resolvermode6: static
    addresses6:
      - 2a01:4f8:212:34cc::9696:9696/64
    resolvers6:
      - 2a01:4f8:0:a0a1::add:1010

network_address_use_slaac: false
