---
network_interfaces:
  - name: eth0
    mode: static
    mode6: disabled
    resolvermode: static
    addresses:
      - 148.251.199.117/32
    resolvers:
      - 213.133.99.99
    routers:
      - 136.243.133.13
  - name: eth1
    mode: disabled
    mode6: static
    resolvermode6: static
    addresses6:
      - 2a01:4f8:212:34cc::9696:9696/64
    resolvers6:
      - 2a01:4f8:0:a0a1::add:1010

network_address_use_slaac: false

acmetool:
  sites:
    - site: terraform.voidlinux.org
      names:
        - terraform.voidlinux.org
    - site: infradocs.voidlinux.org
      names:
        - infradocs.voidlinux.org
  hostmaster_email: postmaster@voidlinux.org
  services:
    - nginx

terrastate_ssl_cert_path: /var/lib/acme/live/terraform.voidlinux.org/fullchain
terrastate_ssl_certkey_path: /var/lib/acme/live/terraform.voidlinux.org/privkey

mdbook_sites:
  - name: infradocs
    root_path: /srv/www/infradocs
    urls:
      - infradocs.voidlinux.org
    source_url: https://github.com/void-linux/void-infrastructure
    source_port: 443
    source_dir: docs
    tls:
      certificate: /var/lib/acme/live/infradocs.voidlinux.org/fullchain
      key: /var/lib/acme/live/infradocs.voidlinux.org/privkey
      stapling: true
