---
- name: Install Packages
  xbps:
    pkg: TerraState
    state: present

- name: Configure Webserver
  include_role:
    name: nginx
    tasks_from: base-site
  vars:
    - site:
        name: terrastate
        static_root: false
        urls:
          - terraform.voidlinux.org
        tls:
          certificate: "{{ terrastate_ssl_cert_path | default('/dev/null') }}"
          key: "{{ terrastate_ssl_certkey_path | default('/dev/null') }}"
          stapling: yes

- name: Install root location block
  copy:
    src: root.conf
    dest: /etc/nginx/locations.d/terraform.voidlinux.org/
    owner: root
    group: root
    mode: 0644
  notify:
    - nginx

- name: Configure Service
  copy:
    src: conf
    dest: /etc/sv/terrastate/conf
    owner: root
    group: root
    mode: 0644
  notify:
    - terrastate

- name: Enable Service
  runit:
    name: terrastate
    enabled: yes
