---
- name: Create Repo Directory
  file:
    path: /srv/www/void-repo
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create Links from hostdir
  file:
    src: "{{ item.src }}"
    dest: "/srv/www/void-repo/{{ item.dst }}"
    state: link
  with_items:
    - { src: /hostdir/binpkgs, dst: current }

- name: Create Static Mirror Directories
  file:
    path: "/srv/www/void-repo/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - distfiles
    - live
    - logos
    - static

- name: Create xlocate group
  group:
    name: xlocate
    state: present

- name: Create xlocate directory
  file:
    path: /srv/www/void-repo/xlocate
    state: directory
    owner: root
    group: xlocate
    mode: 0775
