---
- name: Create Repo Directory
  file:
    path: /srv/www/void-repo
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Create Static Mirror Directories
  file:
    path: "/srv/www/void-repo/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - distfiles
    - live
    - logos
    - static
    - current

- name: Mount the package filesystem into the mirror
  mount:
    fstype: bindfs
    src: /hostdir/binpks
    path: /srv/www/void-repo/current
    state: mounted

- name: Create xlocate group
  group:
    name: xlocate
    state: present

- name: Create xlocate directory
  file:
    path: /srv/www/void-repo/xlocate
    state: directory
    owner: root
    group: xlocate
    mode: 0775
