---
- name: Install Packages
  xbps:
    pkg:
      - mirrorbits
      - geoipupdate
      - snooze
    state: present

- name: Configure geoipupdate service
  copy:
    src: GeoIP.conf
    dest: /etc/GeoIP.conf
    owner: root
    group: root
    mode: 0644

- name: Install geoipupdate service (1/2)
  file:
    path: /etc/sv/geoipupdate
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Install geoipupdate service (2/2)
  copy:
    src: geoipupdate.run
    dest: /etc/sv/geoipupdate/run
    owner: root
    group: root
    mode: 0755

- name: Enable geoipupdate
  service:
    name: geoipupdate
    state: started
    enabled: true

- name: Create config directory
  file:
    path: /etc/mirrorbits
    state: directory
    owner: root
    group: root
    mode: 0755
    
- name: Configure MirrorBits
  template:
    src: config.yml.j2
    dest: /etc/mirrorbits/config.yml
    owner: root
    group: root
    mode: 0644
  notify:
    - mirrorbits

- name: Create log directories
  file:
    path: "/var/log/{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - mirrorbits
    - mirrorbits/trace
    
- name: Install Service (1/2)
  file:
    path: /etc/sv/mirrorbits
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Install Service (2/2)
  copy:
    src: run
    dest: /etc/sv/mirrorbits/run
    owner: root
    group: root
    mode: 0755

- name: Enable Services
  runit:
    name: "{{item}}"
    enabled: true
  with_items:
    - mirrorbits
    - redis

- name: Configure webserver
  include_role:
    name: nginx
    tasks_from: base-site
  vars:
    - site:
        name: auto-mirror
        urls:
          - auto.voidlinux.org
        use_ssl: false
        static_root: false

- name: Configure webserver root location
  copy:
    src: root.conf
    dest: /etc/nginx/locations.d/auto.voidlinux.org/root.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - nginx

