---
- name: Install packages
  xbps:
    pkg:
      - fcgiwrap
      - snooze
      - spawn-fcgi
      - void-man-cgi
      - xmandump
    state: present

- name: Create Group
  group:
    name: xmandump
    system: yes

- name: Create User
  user:
    name: xmandump
    system: yes
    group: xmandump
    home: /var/lib/man-cgi

- name: Create /var/lib/man-cgi
  file:
    path: /var/lib/man-cgi
    state: directory
    owner: xmandump
    group: xmandump
    mode: 0755

- name: Create man trees
  file:
    path: /var/lib/man-cgi/{{item}}
    state: directory
    owner: xmandump
    group: xmandump
    mode: 0755
  with_items:
    - x86_64
    - x86_64-musl
    - armv7l
    - armv7l-musl

- name: Install manpath.conf
  copy:
    src: manpath.conf
    dest: /var/lib/man-cgi/manpath.conf
    owner: root
    group: root
    mode: 0644

- name: Install Update Script
  copy:
    src: update
    dest: /var/lib/man-cgi/update
    owner: root
    group: root
    mode: 0755

- name: Install HTML Fragments
  copy:
    src: "{{item}}"
    dest: /var/lib/man-cgi/{{item}}
    owner: root
    group: root
    mode: 0644
  with_items:
    - header.html
    - footer.html

- name: Install Service (1/2)
  file:
    path: /etc/sv/xmandump
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Install Service (2/2)
  copy:
    src: run
    dest: /etc/sv/xmandump/run
    owner: root
    group: root
    mode: 0755

- name: Install fcgiwrap Service (1/2)
  file:
    path: /etc/sv/fcgiwrap-man
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Install fcgiwrap Service (2/2)
  copy:
    src: run.fcgiwrap
    dest: /etc/sv/fcgiwrap-man/run
    owner: root
    group: root
    mode: 0755

- name: Configure webserver
  include_role:
    name: "{{ VAR_WEBSERVER | default('nginx') }}"
    tasks_from: base-site
  vars:
    - site:
        name: man
        use_ssl: "{{ void_aquire_certs }}"
        urls:
          - man.voidlinux.org
        tls:
          certificate: "{{man_cert_path | default('/dev/null')}}"
          key: "{{man_key_path | default('/dev/null')}}"
          stapling: true
        static_root: false

- name: Install nginx locations block
  copy:
    src: root.conf
    dest: /etc/nginx/locations.d/man.voidlinux.org/root.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - nginx

- name: Enable services
  service:
    name: "{{item}}"
    state: started
    enabled: true
  with_items:
    - fcgiwrap-man
    - xmandump
