---
xbps_repository_main: https://alpha.de.repo.voidlinux.org/current
xbps_repository_nonfree: https://alpha.de.repo.voidlinux.org/current/nonfree
xbps_repository_multilib: https://alpha.de.repo.voidlinux.org/current/multilib
xbps_repository_multilib_nonfree: https://alpha.de.repo.voidlinux.org/current/multilib/nonfree
xbps_repository_address: alpha.de.repo.voidlinux.org
xbps_repository_port: 443

metal_domain_root: '.m.voidlinux.org'
network_hostname: '{{ inventory_hostname | regex_replace(metal_domain_root, "") | regex_replace("\.", "-") }}'
network_fqdn: '{{ inventory_hostname }}'
network_boot_hosts:
  - addr: 161.35.231.145
    name: netauth.voidlinux.org

network_input_policy: DROP
network_output_policy: ACCEPT

# We need to allow arbitrary network forwarding due to the requirement
# that we pass traffic between two different overlay networks.  This
# also technically requires net.ipv4.ip_forward, wich is enabled on
# hosts that require this functionality.
network_forward_policy: ACCEPT

nginx_bind_443: "{{void_aquire_certs}}"
