---
- name: Install nginx and GeoIP
  xbps:
   pkg:
     - nginx
     - libgeoip
   state: present
  when: '"http" in live_mirror_services'

- name: Download GeoIP city database
  get_url:
    url: "{{ live_mirror_GeoIP_citydb_url }}"
    remote_src: yes
    dest: /usr/share/GeoIP/
    owner: root
    group: root
    mode: 0644
  when: '"http" in live_mirror_services'

- name: Expand the GeoIP city database
  command: gunzip GeoLiteCity.dat.gz
  args:
    chdir: /usr/share/GeoIP
    creates: /usr/share/GeoIP/GeoLiteCity.dat
  when: '"http"in live_mirror_services'

- name: Enforce ownership on the GeoIP database
  file:
    path: /usr/share/GeoIP/GeoLiteCity.dat
    state: file
    owner: root
    group: root
    mode: 0644
  when: '"http"in live_mirror_services'

- name: Create the mirror dataroot directory
  file:
    path: "{{ live_mirror_srvdir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Configure firewall rules
  template:
    src: void-mirror.rules.j2
    dest: /etc/iptables.d/void-mirror.rules.j2
    owner: root
    group: root
    mode: 0640
  notify:
    - iptables

- name: Install Diffie-Hellman Parameters
  copy:
    src: dhparam.pem
    dest: /etc/nginx/live_mirror_dhparam.pem
    owner: root
    group: root
    mode: 0644
  notify:
    - nginx
  when:
    - live_mirror_ssl
    - '"http" in live_mirror_services'

- name: Install certbot dependencies
  xbps:
    pkg:
      - base-devel
      - libressl-devel
      - python-devel
      - python-pip
    state: present
  when:
    - live_mirror_ssl
    - live_mirror_letsencrypt
    - '"http" in live_mirror_services'

- name: Install letsencrypt
  pip:
    name: certbot
    state: present
  when:
    - live_mirror_ssl
    - live_mirror_letsencrypt
    - '"http" in live_mirror_services'

- name: Check for certificate
  stat:
    path: "/etc/letsencrypt/live/{{ live_mirror_cert_domain }}/fullchain.pem"
  register: certificate
  when:
    - live_mirror_ssl
    - live_mirror_letsencrypt
    - '"http" in live_mirror_services'

- name: Run Certbot
  command: "certbot certonly --non-interactive --agree-tos --email {{ live_mirror_cert_email }} --standalone -d {{ live_mirror_cert_domain }} --pre-hook 'sv d nginx' --post-hook 'sv u nginx'"
  when:
    - not certificate.stat.exists
    - live_mirror_ssl
    - live_mirror_letsencrypt
    - '"http" in live_mirror_services'

- name: Install cert renewal crontab
  copy:
    src: live_mirror_cert
    dest: /etc/cron.d/live_mirror_cert
    owner: root
    group: root
    mode: 0644
  when:
    - live_mirror_ssl
    - live_mirror_letsencrypt
    - '"http" in live_mirror_services'

- name: Configure nginx
  template:
    src: live-mirror.nginx.conf.j2
    dest: /etc/nginx/sites-available/void-mirror.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - nginx
  when: '"http"in live_mirror_services'

- name: Enable nginx site
  file:
    src: /etc/nginx/sites-available/void-mirror.conf
    dest: /etc/nginx/sites-enabled/void-mirror.conf
    state: link
  notify:
    - nginx
  when: '"http"in live_mirror_services'

- name: Include rsyncd user secrets
  include_vars: secret/live_mirror_syncusers.yml

- name: Configure rsyncd
  template:
    src: void-mirror.rsyncd.conf.j2
    dest: /etc/rsyncd.conf.d/void-mirror.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - rsyncd
  when: '"rsync" in live_mirror_services'

- name: Configure rsyncd secrets
  template:
    src: void-rsyncd.secret.j2
    dest: /etc/void-rsyncd.secret
    owner: root
    group: root
    mode: 0600
  when: live_mirror_securersync

- name: Install sync service secret
  template:
    src: void-mirrorsync.secret.j2
    dest: /etc/void-mirrorsync.secret
    owner: reposync
    group: reposync
    mode: 0400
  no_log: True
  when: not live_mirror_isroot

- name: Install mirror sync service (1/3)
  file:
    path: /etc/sv/void-mirror
    state: directory
    owner: root
    group: root
    mode: 0755
  when: not live_mirror_isroot

- name: Install mirror sync service (2/3)
  template:
    src: run.j2
    dest: /etc/sv/void-mirror/run
    owner: root
    group: root
    mode: 0755
  when: not live_mirror_isroot

- name: Install mirror sync service (3/3)
  file:
    src: /etc/sv/void-mirror
    dest: /var/service/void-mirror
    state: link
  when: not live_mirror_isroot
