---
- name: Install rsync
  xbps: pkg=rsync state=present

- name: Install rsync firewall rules
  copy: src=rsyncd.rules dest=/etc/{{ item }}/rsync.rules owner=root group=root mode=0640
  with_items:
    - iptables.d
    - ip6tables.d
  notify:
    - iptables

- name: Create rsyncd.conf.d
  file: path=/etc/rsyncd.conf.d state=directory owner=root group=root mode=0755

- name: Template rsyncd.conf
  template: src=rsyncd.conf.j2 dest=/etc/rsyncd.conf owner=root mode=root mode=0644
  notify:
    - rsyncd

- name: Enable rsyncd
  file: src=/etc/sv/rsyncd dest=/var/service/rsyncd state=link
  notify:
    - rsyncd
