---
- name: Install rsync
  xbps:
    pkg: rsync
    state: present

- name: Install Sync Keys
  copy:
    src: "{{ item.src }}"
    dest: "/home/{{ buildmaster_repomgr }}/.ssh/{{ item.dst }}"
    owner: "{{ buildmaster_repomgr }}"
    group: "{{ buildmaster_repomgr }}"
    mode: 0400
  with_items:
    - { src: secret/buildmaster_slave_reposync_private, dst: id_ed25519 }
    - { src: secret/buildmaster_slave_reposync_public, dst: id_ed25519.pub }
  loop_control:
    label: "{{ item.src }}"
  no_log: true

# - name: Install Sync Jobs
#   template:
#     src: remote_build_sync.j2
#     dest: /etc/cron.d/{{ item }}_binpkgs-sync
#     owner: root
#     group: root
#     mode: 0644
#   with_items: "{{ buildmaster_remote_zones }}"
