---
- name: Install nginx config
  template:
    src: buildmaster.conf.j2
    dest: /etc/nginx/sites-available/buildmaster.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - nginx

- name: Install dhparam_buildmaster.pem
  copy:
    src: dhparam.pem
    dest: /etc/nginx/dhparam_buildmaster.pem
    owner: root
    group: root
    mode: 0644
    
- name: Enable Buildmaster site
  file:
    src: ../sites-available/buildmaster.conf
    dest: /etc/nginx/sites-enabled/buildmaster.conf
    state: link
  notify:
    - nginx

- name: Install build dependencies
  xbps:
    pkg:
      - base-devel
      - libressl-devel
      - python-devel
      - python-pip
    state: present

- name: Install certbot
  pip:
    name: certbot
    state: present

- name: Check for certificate
  stat:
    path: "/etc/letsencrypt/live/{{ buildmaster_www_servername }}/fullchain.pem"
  register: certificate

- name: Run certbot
  command: "certbot certonly --non-interactive --agree-tos --email {{ buildmaster_cert_email }} --standalone -d {{ certbot_domain }} --pre-hook 'sv d nginx' --post-hook 'sv u nginx'"
  when: not certificate.stat.exists

- name: Install renewal cronjob
  copy:
    src: buildmaster_cert_cronjob
    dest: /etc/cron.d/buildmaster_cert
    owner: root
    group: root
    mode: 0644
