---
- name: Install nginx config
  template:
    src: buildmaster.conf.j2
    dest: /etc/nginx/sites-available/buildmaster.conf
    owner: root
    group: root
    mode: 0644
  notify:
    - nginx

- name: Install dhparam_buildmaster.pem
  copy:
    src: dhparam.pem
    dest: /etc/nginx/dhparam_buildmaster.pem
    owner: root
    group: root
    mode: 0644
    
- name: Enable Buildmaster site
  file:
    src: ../sites-available/buildmaster.conf
    dest: /etc/nginx/sites-enabled/buildmaster.conf
    state: link
  notify:
    - nginx
