# What hostnames should this mirror listen for?  The default is all
# production hostnames for recognized mirrors.
live_mirror_servernames:
  - repo.voidlinux.us
  - repo.voidlinux.fr
  - repo.voidlinux.org
  - repo.voidlinux.com
  - repo.voidlinux.net

# Where is the mirror served from
live_mirror_srvdir: /srv/repo

# Settings for secure rsync
live_mirror_securersync: false

live_mirror_syncusers:
  - desc: Default Sync User
    name: vmirror

# Various sync settings - not needed if master mirror
live_mirror_syncuser: vmirror
live_mirror_syncserver: repo-fi.voidlinux.org
live_mirror_syncsrcdir: voidmirror/
live_mirror_syncdstdir: /srv/repo

# How often to sync with the master mirror, in seconds
live_mirror_sync_interval: 300

# Is this a root mirror (Has a local authoritative builder and
# signer process)?
live_mirror_isroot: false

# What rsync name should the share live under
live_mirror_sharename: voidmirror

# What services should this mirror expose
live_mirror_services:
  - http
  - rsync

# Disable debug packages on this mirror?
live_mirror_nodebug: false
