---
- name: Install packages
  xbps:
    pkg: nomad
    state: present

- name: Make data directory
  file:
    path: /var/lib/nomad
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Make configuration directory
  file:
    path: /etc/nomad
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Install base configuration
  copy:
    src: 25-base.hcl
    dest: /etc/nomad/25-base.hcl
    owner: root
    group: root
    mode: 0644
  notify:
    - nomad

- name: Install Consul Token
  template:
    src: 30-consul.hcl
    dest: /etc/nomad/30-consul.hcl
    owner: root
    group: root
    mode: 0640
  notify:
    - nomad

- name: Set Datacenter
  template:
    src: 25-dc.hcl
    dest: /etc/nomad/25-dc.hcl
    owner: root
    group: root
    mode: 0644
  notify:
    - nomad

- name: Install Service (1/3)
  file:
    path: /etc/sv/{{item}}
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - nomad
    - nomad/log

- name: Install Service (2/3)
  copy:
    src: run
    dest: /etc/sv/nomad/run
    owner: root
    group: root
    mode: 0755

- name: Install Service (3/3)
  copy:
    src: run.log
    dest: /etc/sv/nomad/log/run
    owner: root
    group: root
    mode: 0755

- name: Enable services
  service:
    name: nomad
    enabled: true
    state: started
