---
- hosts: buildmaster
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - acmetool
    - buildmaster
    - root-mirror-shim
    - void-updates
    - live-mirror
    - sources_site

- hosts: buildslave
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - buildslave
