---
- hosts: dxpb-master
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - dxpb/master
    - live-mirror

- hosts: dxpb-worker
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - dxpb/slave
