---
- hosts: hashiworker,hashiproxy,hashimirror
  become: yes
  become_user: root
  become_method: sudo
  vars:
    nomad_role: client
  roles:
    - consul
    - nomad-client


- hosts: hashiproxy,hashimirror
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Accept web traffic
      lineinfile:
        line: "{{item}}"
        path: /etc/iptables.d/proxy.rules
        create: yes
        owner: root
        group: root
        mode: 0640
      with_items:
        - "*filter"
        - "-A INPUT -p tcp --dport 80 -j ACCEPT"
        - "-A INPUT -p tcp --dport 443 -j ACCEPT"
        - "-A INPUT -p tcp --dport 873 -j ACCEPT"
        - "COMMIT"
