---
- name: Configure webserver
  include_role:
    name: nginx
    tasks_from: base-site
  vars:
    - site:
        name: sources
        urls:
          - sources.voidlinux.org
        root_path: /srv/www/sources
        autoindex: true
        tls:
          certificate: "{{ sources_site_cert_path | default('/dev/null') }}"
          key: "{{ sources_site_key_path | default('/dev/null') }}"
          stapling: yes
